version: '3'

services:
  application:
    build: 
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./application:/application
    command: >
      sh -c "python manage.py wait_for_db && 
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=application
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword